// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.programacion2.domain.domain;

import ar.edu.programacion2.domain.domain.Usuario;

privileged aspect Usuario_Roo_JavaBean {
    
    public String Usuario.getNombre() {
        return this.Nombre;
    }
    
    public void Usuario.setNombre(String Nombre) {
        this.Nombre = Nombre;
    }
    
}
