// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.programacion2.domain.domain;

import ar.edu.programacion2.domain.domain.Usuario;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Usuario_Roo_Configurable {
    
    declare @type: Usuario: @Configurable;
    
}
